# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /nfs/ug/homes-0/s/smithqu1/GitHub/research2018/ece532_sdk/lab2/tutorial2/tutorial_2/tutorial_2.srcs/sources_1/bd/design_tutorial_2/ip/design_tutorial_2_microblaze_0_axi_intc_0/design_tutorial_2_microblaze_0_axi_intc_0.xci
# IP: The module: 'design_tutorial_2_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /nfs/ug/homes-0/s/smithqu1/GitHub/research2018/ece532_sdk/lab2/tutorial2/tutorial_2/tutorial_2.srcs/sources_1/bd/design_tutorial_2/ip/design_tutorial_2_microblaze_0_axi_intc_0/design_tutorial_2_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_tutorial_2_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /nfs/ug/homes-0/s/smithqu1/GitHub/research2018/ece532_sdk/lab2/tutorial2/tutorial_2/tutorial_2.srcs/sources_1/bd/design_tutorial_2/ip/design_tutorial_2_microblaze_0_axi_intc_0/design_tutorial_2_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_tutorial_2_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /nfs/ug/homes-0/s/smithqu1/GitHub/research2018/ece532_sdk/lab2/tutorial2/tutorial_2/tutorial_2.srcs/sources_1/bd/design_tutorial_2/ip/design_tutorial_2_microblaze_0_axi_intc_0/design_tutorial_2_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_tutorial_2_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /nfs/ug/homes-0/s/smithqu1/GitHub/research2018/ece532_sdk/lab2/tutorial2/tutorial_2/tutorial_2.srcs/sources_1/bd/design_tutorial_2/ip/design_tutorial_2_microblaze_0_axi_intc_0/design_tutorial_2_microblaze_0_axi_intc_0.xci
# IP: The module: 'design_tutorial_2_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /nfs/ug/homes-0/s/smithqu1/GitHub/research2018/ece532_sdk/lab2/tutorial2/tutorial_2/tutorial_2.srcs/sources_1/bd/design_tutorial_2/ip/design_tutorial_2_microblaze_0_axi_intc_0/design_tutorial_2_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_tutorial_2_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /nfs/ug/homes-0/s/smithqu1/GitHub/research2018/ece532_sdk/lab2/tutorial2/tutorial_2/tutorial_2.srcs/sources_1/bd/design_tutorial_2/ip/design_tutorial_2_microblaze_0_axi_intc_0/design_tutorial_2_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_tutorial_2_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /nfs/ug/homes-0/s/smithqu1/GitHub/research2018/ece532_sdk/lab2/tutorial2/tutorial_2/tutorial_2.srcs/sources_1/bd/design_tutorial_2/ip/design_tutorial_2_microblaze_0_axi_intc_0/design_tutorial_2_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_tutorial_2_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
