# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /nfs/ug/homes-0/s/smithqu1/GitHub/research2018/ece532_sdk/lab2/microblaze1.2.xdc

# Block Designs: bd/design_tutorial_2/design_tutorial_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tutorial_2 || ORIG_REF_NAME==design_tutorial_2} -quiet] -quiet

# IP: bd/design_tutorial_2/ip/design_tutorial_2_microblaze_0_0/design_tutorial_2_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tutorial_2_microblaze_0_0 || ORIG_REF_NAME==design_tutorial_2_microblaze_0_0} -quiet] -quiet

# IP: bd/design_tutorial_2/ip/design_tutorial_2_microblaze_0_axi_periph_0/design_tutorial_2_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tutorial_2_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_tutorial_2_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_tutorial_2/ip/design_tutorial_2_microblaze_0_axi_intc_0/design_tutorial_2_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tutorial_2_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_tutorial_2_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/design_tutorial_2/ip/design_tutorial_2_microblaze_0_xlconcat_0/design_tutorial_2_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tutorial_2_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_tutorial_2_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/design_tutorial_2/ip/design_tutorial_2_mdm_1_0/design_tutorial_2_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tutorial_2_mdm_1_0 || ORIG_REF_NAME==design_tutorial_2_mdm_1_0} -quiet] -quiet

# IP: bd/design_tutorial_2/ip/design_tutorial_2_clk_wiz_1_0/design_tutorial_2_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tutorial_2_clk_wiz_1_0 || ORIG_REF_NAME==design_tutorial_2_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_tutorial_2/ip/design_tutorial_2_rst_clk_wiz_1_100M_0/design_tutorial_2_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tutorial_2_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_tutorial_2_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_tutorial_2/ip/design_tutorial_2_axi_uartlite_0_0/design_tutorial_2_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tutorial_2_axi_uartlite_0_0 || ORIG_REF_NAME==design_tutorial_2_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_tutorial_2/ip/design_tutorial_2_axi_gpio_0_0/design_tutorial_2_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tutorial_2_axi_gpio_0_0 || ORIG_REF_NAME==design_tutorial_2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_tutorial_2/ip/design_tutorial_2_axi_gpio_1_0/design_tutorial_2_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tutorial_2_axi_gpio_1_0 || ORIG_REF_NAME==design_tutorial_2_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_tutorial_2/ip/design_tutorial_2_xbar_0/design_tutorial_2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tutorial_2_xbar_0 || ORIG_REF_NAME==design_tutorial_2_xbar_0} -quiet] -quiet

# IP: bd/design_tutorial_2/ip/design_tutorial_2_dlmb_v10_0/design_tutorial_2_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tutorial_2_dlmb_v10_0 || ORIG_REF_NAME==design_tutorial_2_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_tutorial_2/ip/design_tutorial_2_ilmb_v10_0/design_tutorial_2_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tutorial_2_ilmb_v10_0 || ORIG_REF_NAME==design_tutorial_2_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_tutorial_2/ip/design_tutorial_2_dlmb_bram_if_cntlr_0/design_tutorial_2_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tutorial_2_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_tutorial_2_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_tutorial_2/ip/design_tutorial_2_ilmb_bram_if_cntlr_0/design_tutorial_2_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tutorial_2_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_tutorial_2_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_tutorial_2/ip/design_tutorial_2_lmb_bram_0/design_tutorial_2_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tutorial_2_lmb_bram_0 || ORIG_REF_NAME==design_tutorial_2_lmb_bram_0} -quiet] -quiet

# XDC: bd/design_tutorial_2/design_tutorial_2_ooc.xdc
