webtalk_init -webtalk_dir /nfs/ug/homes-0/s/smithqu1/GitHub/research2018/ece532_sdk/lab2/tutorial2/tutorial_2/tutorial_2.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-05-01 13:44:18" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "mj1r40hrlljd3uimm9fklbc3no" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.1_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 9.4 (stretch)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3999.902 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.734 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1525185490000" -context "sdk\\\\bsp/1525185490000"
webtalk_add_data -client sdk -key hwid -value "1525121180000" -context "sdk\\\\bsp/1525185490000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1525185490000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1525185490000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1525185490000"
webtalk_add_data -client sdk -key uid -value "1525185492000" -context "sdk\\\\application/1525185492000"
webtalk_add_data -client sdk -key hwid -value "1525121180000" -context "sdk\\\\application/1525185492000"
webtalk_add_data -client sdk -key bspid -value "1525185490000" -context "sdk\\\\application/1525185492000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1525185492000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1525185492000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1525185492000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1525185492000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1525185492000"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1525185492000"
webtalk_add_data -client sdk -key projSize -value "88.46875" -context "sdk\\\\application/1525185492000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1525196658699"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1525196658699"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1525196658699"
webtalk_add_data -client sdk -key DebugCount -value "5" -context "sdk\\\\bsp/1525196658699"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1525196658699"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1525196658699"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1525196658699"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1525196658699"
webtalk_transmit -clientid 3508959631 -regid "" -xml /nfs/ug/homes-0/s/smithqu1/GitHub/research2018/ece532_sdk/lab2/tutorial2/tutorial_2/tutorial_2.sdk/webtalk/usage_statistics_ext_sdk.xml -html /nfs/ug/homes-0/s/smithqu1/GitHub/research2018/ece532_sdk/lab2/tutorial2/tutorial_2/tutorial_2.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /nfs/ug/homes-0/s/smithqu1/GitHub/research2018/ece532_sdk/lab2/tutorial2/tutorial_2/tutorial_2.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
