webtalk_init -webtalk_dir /nfs/ug/homes-0/s/smithqu1/GitHub/research2018/ece532_sdk/lab1/vivadotutorial/tutorial_1/tutorial_1.sim/sim_1/behav/xsim/xsim.dir/tutorial_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 30 14:58:50 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ea43e795-1323-4649-83c1-e2394f90a0e3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c7046d760f71418fb2fde778e88b9105" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 9.4 (stretch)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3934.643 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "7680 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "123892_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2447685571 -regid "" -xml /nfs/ug/homes-0/s/smithqu1/GitHub/research2018/ece532_sdk/lab1/vivadotutorial/tutorial_1/tutorial_1.sim/sim_1/behav/xsim/xsim.dir/tutorial_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /nfs/ug/homes-0/s/smithqu1/GitHub/research2018/ece532_sdk/lab1/vivadotutorial/tutorial_1/tutorial_1.sim/sim_1/behav/xsim/xsim.dir/tutorial_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /nfs/ug/homes-0/s/smithqu1/GitHub/research2018/ece532_sdk/lab1/vivadotutorial/tutorial_1/tutorial_1.sim/sim_1/behav/xsim/xsim.dir/tutorial_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
